swagger: '2.0'
info:
  title: Trax API
  description: Documentation for TRAX api application
  version: 1.0.0
host: localhost:8080
basePath: /api
paths:
  /cars:
    get:
      tags:
        - cars
      summary: Get all cars
      description: Returns a list of cars.
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/Car'
              
  /cars/show/{car}:
    get:
      tags:
        - cars
      summary: Find car by ID
      description: Returns a single car
      operationId: getPetById
      parameters:
        - name: car
          in: path
          description: ID of car to return
          required: true
          type: integer
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Car'
            
  /cars/store:
    post:
      tags:
        - cars
      summary: Add a new car
      parameters:
        - in: body
          name: body
          description: Car object that needs to be added
          required: true
          schema:
            type: object
            required:
              - make
              - model
              - year
            properties:
              make:
                type: string
              model:
                type: string
              year:
                type: integer
      responses:
        '200':
          description: successful operation
                
  /cars/destroy/{car}:
    delete:
      tags:
        - cars
      summary: Deletes a car
      parameters:
        - name: car
          in: path
          description: ID of car to delete
          required: true
          type: integer
      responses:
        '200':
          description: successful operation

definitions:
  Car:
    type: object
    properties:
      id:
        type: integer
        example: 1
      make:
        type: string
        example: Land Rover
      model:
        type: string
        example: Range Rover Sport
      year:
        type: integer
        example: 2021